import { SECTION_REGISTRY, SectionType } from "./registry";

export interface DefaultPageConfig {
  slug: string;
  title: string;
  metaDescription: string;
  sections: Array<{
    id: string;
    type: SectionType;
    enabled: boolean;
    order: number;
    data: Record<string, any>;
  }>;
}

export const DEFAULT_PAGES: Record<string, DefaultPageConfig> = {
  home: {
    slug: "home",
    title: "Home",
    metaDescription: "IoT Lab Centre of Excellence & Expothon 2026 at Saveetha School of Engineering, SIMATS.",
    sections: [
      {
        id: "sec-home-hero",
        type: "hero",
        enabled: true,
        order: 0,
        data: SECTION_REGISTRY.hero.defaultData,
      },
      {
        id: "sec-home-stats",
        type: "stats_strip",
        enabled: true,
        order: 1,
        data: SECTION_REGISTRY.stats_strip.defaultData,
      },
      {
        id: "sec-home-about",
        type: "text_image",
        enabled: true,
        order: 2,
        data: SECTION_REGISTRY.text_image.defaultData,
      },
      {
        id: "sec-home-tracks",
        type: "tracks_grid",
        enabled: true,
        order: 3,
        data: SECTION_REGISTRY.tracks_grid.defaultData,
      },
      {
        id: "sec-home-timeline",
        type: "timeline",
        enabled: true,
        order: 4,
        data: SECTION_REGISTRY.timeline.defaultData,
      },
    ],
  },
  about: {
    slug: "about",
    title: "About IoT Lab CoE",
    metaDescription: "Discover research facilities, mission, and equipment at IoT Lab CoE, Saveetha School of Engineering.",
    sections: [
      {
        id: "sec-about-hero",
        type: "hero",
        enabled: true,
        order: 0,
        data: {
          badge: "ABOUT THE COE",
          title: "IoT Lab Centre of Excellence",
          subtitle: "Department of Electronics and Communication Engineering",
          description: "A specialized facility dedicated to sensor instrumentation, embedded firmware engineering, low-power telemetry, and edge microcontroller prototyping at Saveetha School of Engineering, SIMATS.",
          primaryCtaLabel: "Explore Facilities",
          primaryCtaHref: "/facilities",
          secondaryCtaLabel: "View Tracks",
          secondaryCtaHref: "/tracks",
          showCircuitBg: true,
          showStatusBadge: false,
        },
      },
      {
        id: "sec-about-mission",
        type: "text_image",
        enabled: true,
        order: 1,
        data: {
          badge: "RESEARCH MISSION",
          title: "Applied Research in IoT & Embedded Hardware",
          body: "<p>The Centre of Excellence supports undergraduate and postgraduate engineering students in building functional hardware prototypes. Equipped with microcontroller development boards, RF spectrum analyzers, and wireless protocol gateways, the lab enables hands-on experimentation.</p><p>Key focus areas include PCB design, real-time operating systems (FreeRTOS), sensor data acquisition, and low-power WAN communications.</p>",
          imageSlot: "",
          imageAlt: "Saveetha IoT Lab Workspace",
          imagePosition: "right",
          ctaLabel: "View Lab Infrastructure",
          ctaHref: "/facilities",
        },
      },
    ],
  },
  tracks: {
    slug: "tracks",
    title: "Exhibition Tracks",
    metaDescription: "Explore thematic tracks for Expothon 2026 including Smart Healthcare, Edge AI, Smart Agriculture, and Industrial IoT.",
    sections: [
      {
        id: "sec-tracks-hero",
        type: "hero",
        enabled: true,
        order: 0,
        data: {
          badge: "EXHIBITION TRACKS",
          title: "Expothon Innovation Tracks",
          subtitle: "04 Core Engineering Focus Areas",
          description: "Select the track that best corresponds to your embedded system, circuit design, or hardware prototype.",
          primaryCtaLabel: "Submit Project Abstract",
          primaryCtaHref: "/register",
          secondaryCtaLabel: "Rules & Guidelines",
          secondaryCtaHref: "/rules",
          showCircuitBg: true,
          showStatusBadge: true,
        },
      },
      {
        id: "sec-tracks-grid",
        type: "tracks_grid",
        enabled: true,
        order: 1,
        data: SECTION_REGISTRY.tracks_grid.defaultData,
      },
    ],
  },
  rules: {
    slug: "rules",
    title: "Rules & Eligibility Guidelines",
    metaDescription: "Official eligibility criteria, team composition, hardware compliance, and presentation guidelines.",
    sections: [
      {
        id: "sec-rules-hero",
        type: "hero",
        enabled: true,
        order: 0,
        data: {
          badge: "RULES & ELIGIBILITY",
          title: "Participation Rules & Guidelines",
          subtitle: "Framework for Internal & External College Teams",
          description: "Review team size requirements, hardware demo safety rules, and bonafide verification guidelines.",
          primaryCtaLabel: "Register Team",
          primaryCtaHref: "/register",
          secondaryCtaLabel: "Evaluation Rubrics",
          secondaryCtaHref: "/evaluation",
          showCircuitBg: true,
          showStatusBadge: false,
        },
      },
      {
        id: "sec-rules-grid",
        type: "card_grid",
        enabled: true,
        order: 1,
        data: {
          title: "Team & Prototype Guidelines",
          subtitle: "Compliance requirements for all student teams",
          columns: 3,
          cards: [
            {
              badge: "RULE-01",
              title: "Team Composition",
              description: "Teams must consist of 2 to 4 actively enrolled undergraduate or diploma engineering students.",
            },
            {
              badge: "RULE-02",
              title: "Physical Hardware Prototype",
              description: "Every entry must feature a functional physical hardware setup or live testbench. Pure simulations without hardware are not eligible.",
            },
            {
              badge: "RULE-03",
              title: "Institutional Bonafide",
              description: "All participants from external colleges must carry a valid institutional student ID card or bonafide letter from their department head.",
            },
            {
              badge: "RULE-04",
              title: "Originality & Safety",
              description: "Work must be the original contribution of team members. High-voltage setups must adhere to electrical safety and isolation guidelines.",
            },
            {
              badge: "RULE-05",
              title: "Faculty Mentorship",
              description: "Teams may be guided by a designated faculty mentor from their home institution, identified during registration.",
            },
            {
              badge: "RULE-06",
              title: "Jury Decision",
              description: "The technical evaluation and final decision made by the jury panel is final and binding on all participating teams.",
            },
          ],
        },
      },
    ],
  },
  evaluation: {
    slug: "evaluation",
    title: "Evaluation Rubrics & Scoring",
    metaDescription: "Standardized jury scoring criteria and evaluation rubrics for Expothon.",
    sections: [
      {
        id: "sec-eval-hero",
        type: "hero",
        enabled: true,
        order: 0,
        data: {
          badge: "EVALUATION RUBRICS",
          title: "Jury Scoring Criteria",
          subtitle: "Standardized Evaluation Parameters",
          description: "All projects are evaluated across circuit architecture, firmware quality, practical problem relevance, and live demonstration.",
          primaryCtaLabel: "Submit Project Abstract",
          primaryCtaHref: "/register",
          secondaryCtaLabel: "View Awards",
          secondaryCtaHref: "/awards",
          showCircuitBg: true,
          showStatusBadge: false,
        },
      },
      {
        id: "sec-eval-criteria",
        type: "judging_criteria",
        enabled: true,
        order: 1,
        data: SECTION_REGISTRY.judging_criteria.defaultData,
      },
    ],
  },
  schedule: {
    slug: "schedule",
    title: "Event Schedule & Key Dates",
    metaDescription: "Important milestones for abstract submission, shortlisting, and physical exhibition day.",
    sections: [
      {
        id: "sec-sched-hero",
        type: "hero",
        enabled: true,
        order: 0,
        data: {
          badge: "SCHEDULE",
          title: "Key Dates & Milestones",
          subtitle: "Event Schedule for Expothon 2026",
          description: "Track submission deadlines, shortlisting notification dates, and exhibition day details.",
          primaryCtaLabel: "Register Now",
          primaryCtaHref: "/register",
          secondaryCtaLabel: "Check Status",
          secondaryCtaHref: "/registration-status",
          showCircuitBg: true,
          showStatusBadge: true,
        },
      },
      {
        id: "sec-sched-timeline",
        type: "timeline",
        enabled: true,
        order: 1,
        data: SECTION_REGISTRY.timeline.defaultData,
      },
    ],
  },
  awards: {
    slug: "awards",
    title: "Awards & Recognition",
    metaDescription: "Prize tiers, merit awards, certificates, and recognition categories for Expothon.",
    sections: [
      {
        id: "sec-awards-hero",
        type: "hero",
        enabled: true,
        order: 0,
        data: {
          badge: "AWARDS & PRIZES",
          title: "Awards & Recognition",
          subtitle: "Honoring Outstanding Engineering Prototypes",
          description: "Trophies, merit certificates, and cash awards for winning projects across all thematic tracks.",
          primaryCtaLabel: "Submit Abstract",
          primaryCtaHref: "/register",
          secondaryCtaLabel: "Evaluation Rubrics",
          secondaryCtaHref: "/evaluation",
          showCircuitBg: true,
          showStatusBadge: false,
        },
      },
      {
        id: "sec-awards-list",
        type: "awards_prizes",
        enabled: true,
        order: 1,
        data: SECTION_REGISTRY.awards_prizes.defaultData,
      },
    ],
  },
  facilities: {
    slug: "facilities",
    title: "IoT Lab Infrastructure & Facilities",
    metaDescription: "Specialized workstations, microcontroller benches, RF equipment, and sensor testbeds.",
    sections: [
      {
        id: "sec-fac-hero",
        type: "hero",
        enabled: true,
        order: 0,
        data: {
          badge: "LAB INFRASTRUCTURE",
          title: "Laboratory Infrastructure",
          subtitle: "Hardware Testbeds & Measurement Equipment",
          description: "Equipped with embedded development boards, wireless protocol analyzers, digital storage oscilloscopes, and edge sensor stations.",
          primaryCtaLabel: "Contact Coordinators",
          primaryCtaHref: "/contact",
          secondaryCtaLabel: "Explore Tracks",
          secondaryCtaHref: "/tracks",
          showCircuitBg: true,
          showStatusBadge: false,
        },
      },
      {
        id: "sec-fac-grid",
        type: "card_grid",
        enabled: true,
        order: 1,
        data: {
          title: "Specialized Testing Benches",
          subtitle: "Hardware prototyping and measurement stations",
          columns: 3,
          cards: [
            {
              badge: "STATION-01",
              title: "Embedded Processing Testbed",
              description: "Equipped with STM32 ARM Cortex-M processors, ESP32-S3 boards, Raspberry Pi edge nodes, and hardware in-circuit debuggers.",
            },
            {
              badge: "STATION-02",
              title: "RF & Wireless Telemetry Station",
              description: "Dedicated LoRaWAN 868MHz gateways, BLE 5.3 beacons, Zigbee mesh testbeds, and digital spectrum analyzers.",
            },
            {
              badge: "STATION-03",
              title: "Sensor Acquisition & Power Analytics",
              description: "Digital storage oscilloscopes (DSO), logic analyzers, power profiling units, and industrial sensor suites.",
            },
          ],
        },
      },
    ],
  },
  team: {
    slug: "team",
    title: "Organizing Committee",
    metaDescription: "Faculty coordinators and student committee members for the IoT Lab CoE.",
    sections: [
      {
        id: "sec-team-hero",
        type: "hero",
        enabled: true,
        order: 0,
        data: {
          badge: "ORGANIZING COMMITTEE",
          title: "Organizing Committee",
          subtitle: "Department of Electronics & Communication Engineering",
          description: "Faculty coordinators and student convenors managing the IoT Lab Centre of Excellence and Expothon 2026.",
          primaryCtaLabel: "Contact Desk",
          primaryCtaHref: "/contact",
          secondaryCtaLabel: "Expothon Details",
          secondaryCtaHref: "/expothon",
          showCircuitBg: true,
          showStatusBadge: false,
        },
      },
      {
        id: "sec-team-grid",
        type: "team_grid",
        enabled: true,
        order: 1,
        data: SECTION_REGISTRY.team_grid.defaultData,
      },
    ],
  },
  faq: {
    slug: "faq",
    title: "Frequently Asked Questions",
    metaDescription: "Answers to common queries on Expothon registration, hardware demo logistics, and certificates.",
    sections: [
      {
        id: "sec-faq-hero",
        type: "hero",
        enabled: true,
        order: 0,
        data: {
          badge: "FAQS",
          title: "Frequently Asked Questions",
          subtitle: "Guidance for Participating Teams and Mentors",
          description: "Find clear answers to common questions regarding registration, hardware demonstration, and evaluation.",
          primaryCtaLabel: "Register Team",
          primaryCtaHref: "/register",
          secondaryCtaLabel: "Contact Us",
          secondaryCtaHref: "/contact",
          showCircuitBg: true,
          showStatusBadge: false,
        },
      },
      {
        id: "sec-faq-accordion",
        type: "faq_accordion",
        enabled: true,
        order: 1,
        data: SECTION_REGISTRY.faq_accordion.defaultData,
      },
    ],
  },
  downloads: {
    slug: "downloads",
    title: "Official Downloads",
    metaDescription: "Download the official Expothon brochure, detailed rulebook, and bonafide NOC templates.",
    sections: [
      {
        id: "sec-down-hero",
        type: "hero",
        enabled: true,
        order: 0,
        data: {
          badge: "DOWNLOADS",
          title: "Official Documents & Templates",
          subtitle: "Event Circulars, Formats & Guidelines",
          description: "Download authorized event circulars, abstract formatting guidelines, and institutional permission formats.",
          primaryCtaLabel: "Register Online",
          primaryCtaHref: "/register",
          secondaryCtaLabel: "View Tracks",
          secondaryCtaHref: "/tracks",
          showCircuitBg: true,
          showStatusBadge: false,
        },
      },
      {
        id: "sec-down-files",
        type: "downloads",
        enabled: true,
        order: 1,
        data: SECTION_REGISTRY.downloads.defaultData,
      },
    ],
  },
  expothon: {
    slug: "expothon",
    title: "Expothon 2026 - Project Exhibition",
    metaDescription: "Expothon 2026 National-Level Project Exhibition at Saveetha IoT CoE.",
    sections: [
      {
        id: "sec-exp-hero",
        type: "hero",
        enabled: true,
        order: 0,
        data: {
          badge: "EXPOTHON 2026",
          title: "Expothon 2026",
          subtitle: "National-Level IoT & Embedded Systems Project Exhibition",
          description: "An on-campus project exhibition providing student teams with a platform to demonstrate functional hardware prototypes before an expert jury.",
          primaryCtaLabel: "Submit Project Abstract",
          primaryCtaHref: "/register",
          secondaryCtaLabel: "Explore Tracks",
          secondaryCtaHref: "/tracks",
          showCircuitBg: true,
          showStatusBadge: true,
        },
      },
      {
        id: "sec-exp-tracks",
        type: "tracks_grid",
        enabled: true,
        order: 1,
        data: SECTION_REGISTRY.tracks_grid.defaultData,
      },
      {
        id: "sec-exp-timeline",
        type: "timeline",
        enabled: true,
        order: 2,
        data: SECTION_REGISTRY.timeline.defaultData,
      },
    ],
  },
  "code-of-conduct": {
    slug: "code-of-conduct",
    title: "Code of Conduct",
    metaDescription: "Code of conduct and ethical standards for participants at Expothon 2026.",
    sections: [
      {
        id: "sec-coc-hero",
        type: "hero",
        enabled: true,
        order: 0,
        data: {
          badge: "POLICY",
          title: "Code of Conduct",
          subtitle: "Ethical Standards & Laboratory Safety",
          description: "Guidelines governing participant integrity, fair competition, and workplace safety.",
          showCircuitBg: false,
          showStatusBadge: false,
        },
      },
      {
        id: "sec-coc-body",
        type: "rich_text",
        enabled: true,
        order: 1,
        data: {
          title: "Code of Conduct",
          content: "<p>All participants, mentors, and attendees are expected to conduct themselves with integrity, professionalism, and mutual respect.</p><p>Hardware demonstrations must adhere strictly to laboratory electrical safety protocols. Plagiarism or misrepresentation of work will lead to immediate disqualification.</p>",
        },
      },
    ],
  },
  terms: {
    slug: "terms",
    title: "Terms and Conditions",
    metaDescription: "Official terms and conditions for Expothon 2026 participation.",
    sections: [
      {
        id: "sec-terms-hero",
        type: "hero",
        enabled: true,
        order: 0,
        data: {
          badge: "POLICY",
          title: "Terms and Conditions",
          subtitle: "Participation Terms for Expothon 2026",
          description: "Terms governing registration, project exhibition, and jury decisions.",
          showCircuitBg: false,
          showStatusBadge: false,
        },
      },
      {
        id: "sec-terms-body",
        type: "rich_text",
        enabled: true,
        order: 1,
        data: {
          title: "Terms of Participation",
          content: "<p>By registering for Expothon 2026, teams agree that submitted abstracts represent their original technical work.</p><p>The decisions of the evaluation jury are final. Shortlisted teams are responsible for the safe transport of their prototype hardware to the venue.</p>",
        },
      },
    ],
  },
  privacy: {
    slug: "privacy",
    title: "Privacy Policy",
    metaDescription: "Data handling and privacy guidelines for Expothon participants.",
    sections: [
      {
        id: "sec-priv-hero",
        type: "hero",
        enabled: true,
        order: 0,
        data: {
          badge: "POLICY",
          title: "Privacy Policy",
          subtitle: "Participant Data Protection",
          description: "How participant information is collected and managed for event operations.",
          showCircuitBg: false,
          showStatusBadge: false,
        },
      },
      {
        id: "sec-priv-body",
        type: "rich_text",
        enabled: true,
        order: 1,
        data: {
          title: "Data Handling",
          content: "<p>Information submitted during registration (including team member names, institutional emails, and phone numbers) is used strictly for event coordination, verification, and certificate issuance.</p><p>Participant data will not be shared with third parties or used for unrelated commercial marketing.</p>",
        },
      },
    ],
  },
};
